apiVersion: v1
kind: ConfigMap
metadata:
  name: placeholder-configname
  labels:
    theiacloud: proxy
  namespace: placeholder-namespace
  ownerReferences:
    - apiVersion: theia.cloud/v8beta
      kind: AppDefinition
      name: placeholder
      uid: placeholder
data:
