apiVersion: v1
kind: ConfigMap
metadata:
  name: placeholder-configname
  namespace: placeholder-namespace
  ownerReferences:
    - apiVersion: theia.cloud/v2alpha
      kind: Template
      name: placeholder
      uid: placeholder
data:
