apiVersion: v1
kind: ConfigMap
metadata:
  name: placeholder-configname
  labels:
    theia-cloud.io/template-purpose: proxy
  namespace: placeholder-namespace
  ownerReferences:
    - apiVersion: theia.cloud/v1beta9
      kind: AppDefinition
      name: placeholder
      uid: placeholder
data:
