apiVersion: v1
kind: PersistentVolume
metadata:
  name: placeholder-pv
  namespace: placeholder-namespace
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 250Mi
  hostPath:
    path: /data/test/placeholder-pv/