apiVersion: v1
kind: Service
metadata:
  name: placeholder-servicename
  labels:
    app: placeholder-app
  namespace: placeholder-namespace
  ownerReferences:
    - apiVersion: theia.cloud/v1beta9
      kind: AppDefinition
      name: placeholder
      uid: placeholder
spec:
  ports:
    - name: http
      port: placeholder-port 
      protocol: TCP
      targetPort: application
    placeholder-monitor-port

  selector:
    app: placeholder-app
  type: ClusterIP
