appId: asdfghjkl

issuer:
  email: mmorlock@example.com

hosts:
  workspace: workspace.192.168.39.173.nip.io
  landing: theia.cloud.192.168.39.173.nip.io
  instance: ws.192.168.39.173.nip.io

landingPage:
  image: theiacloud/theia-cloud-landing-page
  template: "theia-cloud-demo"

keycloak:
  enable: true
  authUrl: "https://34.120.110.14.nip.io/"
  realm: "TheiaCloud"
  clientId: "theia-cloud"
  clientSecret: "zpF6PUpM3RmfVecInloasXTjn1yc88Dp"
  cookieSecret: "OQINaROshtE9TcZkNAm5Zs2Pv3xaWytBmc5W7sPX7ws="

operator:
  image: theiacloud/theia-cloud-operator
  eagerStart: false
  ephemeralStorage: true
  cloudProvider: "K8S"
  bandwidthLimiter: "K8SANNOTATION"

workspace:
  image: theiacloud/theia-cloud-workspace

ingress:
  instanceName: "theia-cloud-demo-ws-ingress"
  clusterIssuer: letsencrypt-prod
  theiaCloudCommonName: false