app:
  id: asdfghjkl
  name: Theia Blueprint
  logo: theiablueprint.png

issuer:
  email: mmorlock@example.com

image:
  name: theiacloud/theia-cloud-demo

hosts:
  workspace: workspace.192.168.39.3.nip.io
  landing: theia.cloud.192.168.39.3.nip.io
  instance: ws.192.168.39.3.nip.io

landingPage:
  image: theiacloud/theia-cloud-landing-page
  appDefinition: "theia-cloud-demo"

keycloak:
  enable: true
  authUrl: "https://keycloak.192.168.39.3.nip.io/auth/"
  realm: "TheiaCloud"
  clientId: "theia-cloud"
  clientSecret: "publicbutoauth2proxywantsasecret"
  cookieSecret: "OQINaROshtE9TcZkNAm5Zs2Pv3xaWytBmc5W7sPX7ws="

operator:
  image: theiacloud/theia-cloud-operator
  eagerStart: false
  ephemeralStorage: false
  cloudProvider: "K8S"
  bandwidthLimiter: "K8SANNOTATION"

workspace:
  image: theiacloud/theia-cloud-workspace

ingress:
  instanceName: "theia-cloud-demo-ws-ingress"
  clusterIssuer: theia-cloud-selfsigned-issuer
  theiaCloudCommonName: true
