app:
  id: asdfghjkl
  name: CDT.cloud Blueprint
  logo: cdtcloud.png

issuer:
  email: jfaltermeier@eclipsesource.com

image:
  name: theiacloud/cdt-blueprint

hosts:
  workspace: workspace.34.159.89.224.nip.io
  landing: theia.cloud.34.159.89.224.nip.io
  instance: ws.34.159.89.224.nip.io

landingPage:
  image: theiacloud/theia-cloud-try-now-page
  template: "theia-cloud-demo"

keycloak:
  enable: false
  authUrl: ""
  realm: ""
  clientId: ""
  clientSecret: ""
  cookieSecret: ""

operator:
  image: theiacloud/theia-cloud-operator
  eagerStart: false
  ephemeralStorage: true
  cloudProvider: "GKE"
  bandwidthLimiter: "WONDERSHAPER"

workspace:
  image: theiacloud/theia-cloud-workspace

ingress:
  instanceName: "theia-cloud-demo-ws-ingress"
  clusterIssuer: letsencrypt-prod
  theiaCloudCommonName: false
