appId: asdfghjkl

issuer:
  email: jfaltermeier@eclipsesource.com

hosts:
  workspace: workspace.34.141.62.32.nip.io
  landing: theia.cloud.34.141.62.32.nip.io
  instance: ws.34.141.62.32.nip.io

landingPage:
  image: eu.gcr.io/kubernetes-238012/theia-cloud-landing-page
  template: "theia-cloud-demo"

keycloak:
  enable: false
  authUrl: ""
  realm: ""
  clientId: ""
  clientSecret: ""
  cookieSecret: ""
  
operator:
  image: eu.gcr.io/kubernetes-238012/theia-cloud-operator
  eagerStart: false
  ephemeralStorage: true
  cloudProvider: "GKE"
  bandwidthLimiter: "WONDERSHAPER"

workspace:
  image: eu.gcr.io/kubernetes-238012/theia-cloud-workspace

ingress:
  instanceName: "theia-cloud-demo-ws-ingress"
  clusterIssuer: letsencrypt-prod
  theiaCloudCommonName: false