appId: asdfghjkl

issuer:
  email: mmorlock@example.com

hosts:
  workspace: workspace.192.168.39.3.nip.io
  landing: theia.cloud.192.168.39.3.nip.io
  instance: ws.192.168.39.3.nip.io

landingPage:
  image: eu.gcr.io/kubernetes-238012/theia-cloud-landing-page
  template: "theia-cloud-demo"

keycloak:
  enable: true
  authUrl: "https://keycloak.192.168.39.3.nip.io/auth/"
  realm: "TheiaCloud"
  clientId: "theia-cloud"
  clientSecret: "zpF6PUpM3RmfVecInloasXTjn1yc88Dp"
  cookieSecret: "OQINaROshtE9TcZkNAm5Zs2Pv3xaWytBmc5W7sPX7ws="

operator:
  image: eu.gcr.io/kubernetes-238012/theia-cloud-operator
  eagerStart: false
  ephemeralStorage: false
  cloudProvider: "K8S"
  bandwidthLimiter: "K8SANNOTATION"

workspace:
  image: eu.gcr.io/kubernetes-238012/theia-cloud-workspace

ingress:
  instanceName: "theia-cloud-demo-ws-ingress"
  clusterIssuer: theia-cloud-selfsigned-issuer
  theiaCloudCommonName: true