app:
  id: asdfghjkl
  name: Theia Blueprint
  logo: theiablueprint.png

issuer:
  email: jfaltermeier@eclipsesource.com

image:
  name: theiacloud/theia-cloud-demo

hosts:
  service: service.34.141.62.32.nip.io
  landing: theia.cloud.34.141.62.32.nip.io
  instance: ws.34.141.62.32.nip.io

landingPage:
  image: theiacloud/theia-cloud-try-now-page
  appDefinition: "theia-cloud-demo"

keycloak:
  enable: false
  authUrl: ""
  realm: ""
  clientId: ""
  clientSecret: ""
  cookieSecret: ""

operator:
  image: theiacloud/theia-cloud-operator
  eagerStart: false
  ephemeralStorage: true
  cloudProvider: "GKE"
  bandwidthLimiter: "WONDERSHAPER"

service:
  image: theiacloud/theia-cloud-service

ingress:
  instanceName: "theia-cloud-demo-ws-ingress"
  clusterIssuer: letsencrypt-prod
  theiaCloudCommonName: false
