imagePullPolicy: Always

app:
  id: asdfghjkl
  name: Theia Blueprint

issuer:
  email: jfaltermeier@eclipsesource.com

demoApplication:
  name: theiacloud/theia-cloud-demo:0.11.0-next
  pullSecret: ""
  timeoutStrategy: "FIXEDTIME"
  timeoutLimit: "30"
  imagePullPolicy: IfNotPresent
  monitor: null

hosts:
  usePaths: false
  service: service.theia-cloud.io
  serviceProtocol: https
  landing: try.theia-cloud.io
  instance: ws.theia-cloud.io

landingPage:
  image: theiacloud/theia-cloud-try-now-page:0.11.0-next
  appDefinition: "theia-cloud-demo"
  ephemeralStorage: true
  additionalApps:
    coffee-editor:
      label: "Coffee Editor"
    cdt-cloud-demo:
      label: "CDT.cloud Blueprint"

keycloak:
  enable: true
  authUrl: "https://keycloak.theia-cloud.io/"
  keycloakRealm: "TheiaCloud"
  keycloakClientId: "theia-cloud"
  clientSecret: "publicbutoauth2proxywantsasecret"
  cookieSecret: "s-p4GxfRlPa_BI1XsLuvE2ihNOqYD1vmewWcXcpYjr0="

operator:
  eagerStart: false
  bandwidthLimiter: "WONDERSHAPER"
  sessionsPerUser: "3"

ingress:
  instanceName: "theia-cloud-demo-ws-ingress"
  clusterIssuer: letsencrypt-prod
  theiaCloudCommonName: false

monitor:
  enable: false
