imagePullPolicy: IfNotPresent

app:
  id: asdfghjkl
  name: Theia Blueprint

issuer:
  email: jfaltermeier@eclipsesource.com

demoApplication:
  name: theiacloud/theia-cloud-demo:1.1.0-next
  pullSecret: ""
  timeoutStrategy: "FIXEDTIME"
  timeoutLimit: "30"
  imagePullPolicy: IfNotPresent
  monitor: null

hosts:
  usePaths: false
  configuration:
    baseHost: theia-cloud.io
    service: service
    landing: try
    instance: ws

landingPage:
  image: theiacloud/theia-cloud-landing-page:1.1.0-next
  appDefinition: "theia-cloud-demo"
  ephemeralStorage: true
  additionalApps:
    coffee-editor:
      label: "Coffee Editor"
    cdt-cloud-demo:
      label: "CDT.cloud Blueprint"

keycloak:
  enable: true
  authUrl: "https://keycloak.theia-cloud.io/"
  keycloakRealm: "TheiaCloud"
  keycloakClientId: "theia-cloud"
  clientSecret: "publicbutoauth2proxywantsasecret"
  cookieSecret: "s-p4GxfRlPa_BI1XsLuvE2ihNOqYD1vmewWcXcpYjr0="

service:
  protocol: https

operator:
  eagerStart: false
  bandwidthLimiter: "WONDERSHAPER"
  sessionsPerUser: "3"

ingress:
  clusterIssuer: letsencrypt-prod
  theiaCloudCommonName: false
  instances:
    name: "theia-cloud-demo-ws-ingress"

monitor:
  enable: false
