/* tslint:disable */
/* eslint-disable */
/**
 * Theia.cloud API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Request to list workspaces of a user.
 * @export
 * @interface WorkspaceListRequest
 */
export interface WorkspaceListRequest {
    /**
     * The App Id of this Theia.cloud instance. Request without a matching Id will be denied.
     * @type {string}
     * @memberof WorkspaceListRequest
     */
    appId: string;
    /**
     * The user identification, usually the email address.
     * @type {string}
     * @memberof WorkspaceListRequest
     */
    user: string;
}

/**
 * Check if a given object implements the WorkspaceListRequest interface.
 */
export function instanceOfWorkspaceListRequest(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'appId' in value;
  isInstance = isInstance && 'user' in value;

  return isInstance;
}

export function WorkspaceListRequestFromJSON(json: any): WorkspaceListRequest {
  return WorkspaceListRequestFromJSONTyped(json, false);
}

export function WorkspaceListRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkspaceListRequest {
  if ((json === undefined) || (json === null)) {
    return json;
  }
  return {

    'appId': json['appId'],
    'user': json['user']
  };
}

export function WorkspaceListRequestToJSON(value?: WorkspaceListRequest | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {

    'appId': value.appId,
    'user': value.user
  };
}

