/* tslint:disable */
/* eslint-disable */
/**
 * Theia.cloud API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
import type { WorkspaceCreationResponseWorkspace } from './WorkspaceCreationResponseWorkspace';
import {
    WorkspaceCreationResponseWorkspaceFromJSON, WorkspaceCreationResponseWorkspaceToJSON
} from './WorkspaceCreationResponseWorkspace';

/**
 * Response of a workspace creation. Allows to retrieve whether the creation was successfull or to get the error that occurred.
 * @export
 * @interface WorkspaceCreationResponse
 */
export interface WorkspaceCreationResponse {
    /**
     * Specifies which kind of response this is. This is optional.
     * @type {string}
     * @memberof WorkspaceCreationResponse
     */
    kind?: string;
    /**
     * Whether the request was successful
     * @type {boolean}
     * @memberof WorkspaceCreationResponse
     */
    success: boolean;
    /**
     * The error message. Empty if request was successful.
     * @type {string}
     * @memberof WorkspaceCreationResponse
     */
    error?: string;
    /**
     * 
     * @type {WorkspaceCreationResponseWorkspace}
     * @memberof WorkspaceCreationResponse
     */
    workspace: WorkspaceCreationResponseWorkspace;
}

/**
 * Check if a given object implements the WorkspaceCreationResponse interface.
 */
export function instanceOfWorkspaceCreationResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "success" in value;
    isInstance = isInstance && "workspace" in value;

    return isInstance;
}

export function WorkspaceCreationResponseFromJSON(json: any): WorkspaceCreationResponse {
    return WorkspaceCreationResponseFromJSONTyped(json, false);
}

export function WorkspaceCreationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkspaceCreationResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'kind': !exists(json, 'kind') ? undefined : json['kind'],
        'success': json['success'],
        'error': !exists(json, 'error') ? undefined : json['error'],
        'workspace': WorkspaceCreationResponseWorkspaceFromJSON(json['workspace']),
    };
}

export function WorkspaceCreationResponseToJSON(value?: WorkspaceCreationResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'kind': value.kind,
        'success': value.success,
        'error': value.error,
        'workspace': WorkspaceCreationResponseWorkspaceToJSON(value.workspace),
    };
}

