apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth2-proxy-config
  namespace: {{ .Release.Namespace }}
data:
  oauth2-proxy.cfg: |+
    # Provider config
    provider="keycloak-oidc"
    redirect_url="https://placeholder/oauth2/callback"
    oidc_issuer_url="{{ tpl (.Values.keycloak.authUrl | toString) . }}realms/{{ tpl (.Values.keycloak.realm | toString) . }}"
    ssl_insecure_skip_verify=true
    # Client config
    client_id="{{ tpl (.Values.keycloak.clientId | toString) . }}"
    client_secret="{{ tpl (.Values.keycloak.clientSecret | toString) . }}"
    cookie_secret="{{ tpl (.Values.keycloak.cookieSecret | toString) . }}"
    cookie_secure="false"
    #proxy_prefix=""
    # Upstream config
    http_address="0.0.0.0:5000"
    upstreams="http://127.0.0.1:placeholder-port/"
    # Proxy Config
    #user_id_claim="preferred_username"
    skip_auth_routes=["/health.*"]
    skip_provider_button="true"
    reverse_proxy="true"
    # email_domains=["*"]
    cookie_domains=["{{ tpl (.Values.hosts.instance | toString) . }}"]
    whitelist_domains=["{{ tpl (.Values.hosts.instance | toString) . }}:*",".google.com:*"]
    custom_templates_dir="/templates"
