apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator-deployment
  labels:
    app: operator
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operator
  template:
    metadata:
      labels:
        app: operator
    spec:
      # we need to be able to create and read operators
      automountServiceAccountToken: true
      serviceAccountName: operator-api-service-account
      containers:
      - name: operator-container
        image: {{ tpl (.Values.operator.image | toString) . }}
        args:
          {{ if .Values.keycloak.enable }}- "--keycloak"{{ end }}
          {{ if .Values.operator.eagerStart }}- "--eagerStart"{{ end }}
          - "--cloudProvider"
          - {{ tpl (.Values.operator.cloudProvider | toString) . }}
          - "--bandwidthLimiter"
          - {{ tpl (.Values.operator.bandwidthLimiter | toString) . }}
          - "--serviceUrl"
          - {{ tpl (.Values.hosts.serviceProtocol | toString) . }}://{{ tpl (.Values.hosts.service | toString) . }}{{ if .Values.hosts.useServicePortInHostname }}:{{ tpl (.Values.hosts.servicePort | toString) . }}{{ end }}
          - "--sessionsPerUser"
          - "{{ tpl (.Values.operator.sessionsPerUser | toString) . }}"
          - "--appId"
          - {{ tpl (.Values.app.id | toString) . }}
      {{- if .Values.operator.imagePullSecret }}
      imagePullSecrets:
        - name: {{ tpl (.Values.operator.imagePullSecret | toString) . }}
      {{- end }}