apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: {{ tpl (.Values.ingress.clusterIssuer | toString) . }}
    acme.cert-manager.io/http01-edit-in-place: "true"
  namespace: {{ .Release.Namespace }}
spec:
  tls: 
  - hosts:
    - {{ tpl (.Values.hosts.service | toString) . }}
    secretName: service-cert-secret
  rules:
  - host: {{ tpl (.Values.hosts.service | toString) . }}
    http:
      paths:
      - backend:
          service:
            name: service-service
            port:
              number: {{ tpl (.Values.hosts.servicePort | toString) . }}
        path: /service
        pathType: ImplementationSpecific