apiVersion: v1
kind: ConfigMap
metadata:
  name: service-config
  namespace: {{ .Release.Namespace }}
data:
  APPID: {{ tpl (.Values.app.id | toString) . }}
  SERVICE_PORT: {{ tpl (.Values.hosts.servicePort | toString) . | quote }}
  KEYCLOAK_ENABLE: {{ tpl (.Values.keycloak.enable | toString) . | quote }}
  {{- if eq (tpl (.Values.keycloak.enable | toString) .) "true" }}
  KEYCLOAK_SERVERURL: {{ tpl (.Values.keycloak.authUrl | toString) . }}realms/{{ tpl (.Values.keycloak.realm | toString) . }}
  KEYCLOAK_CLIENTID: {{ tpl (.Values.keycloak.clientId | toString) . }}
  KEYCLOAK_CLIENTSECRET: {{ tpl (.Values.keycloak.clientSecret | toString) . }}
  {{- end }}