apiVersion: theia.cloud/v3beta
kind: AppDefinition
metadata:
  name: theia-cloud-demo
spec:
  name: theia-cloud-demo
  image: {{ tpl (.Values.image.name | toString) . }}
  imagePullPolicy: {{ if .Values.image.imagePullPolicy }}{{ tpl (.Values.image.imagePullPolicy | toString) . }}{{ else }}{{ tpl (.Values.imagePullPolicy | toString) . }}{{ end }}
  pullSecret: {{ tpl (.Values.image.pullSecret | toString) . }}
  uid: 101
  port: 3000
  {{- if .Values.hosts.usePaths }}
  host: {{ tpl (.Values.hosts.paths.baseHost | toString) . }}
  {{- else }}
  host: {{ tpl (.Values.hosts.instance | toString) . }}
  {{- end }}
  ingressname: {{ tpl (.Values.ingress.instanceName | toString) . }}
  minInstances: 0
  maxInstances: 10
  timeout:
    limit: {{ tpl (.Values.image.timeoutLimit | toString) . }}
    strategy: {{ tpl (.Values.image.timeoutStrategy | toString) . }}
  requestsMemory: 1000M
  limitsMemory: 1200M
  requestsCpu: "100m"
  limitsCpu: "2"
  downlinkLimit: 30000
  uplinkLimit: 30000
  mountPath: "/home/project/persisted"
