apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: workspace-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer }}
    acme.cert-manager.io/http01-edit-in-place: "true"
  namespace: {{ .Release.Namespace }}
spec:
  tls: 
  - hosts:
    - {{ .Values.hosts.workspace }}
    secretName: workspace-cert-secret
  rules:
  - host: {{ .Values.hosts.workspace }}
    http:
      paths:
      - backend:
          service:
            name: workspace-service
            port:
              number: 8081
        path: /workspaces
        pathType: ImplementationSpecific