appId: asdfghjkl

issuer:
  email: mmorlock@example.com

hosts:
  workspace: workspace.192.168.39.173.nip.io
  landing: theia.cloud.192.168.39.173.nip.io
  instance: ws.192.168.39.173.nip.io

landingPage:
  template: "theia-cloud-demo"

keycloak:
  enable: true
  authUrl: "https://34.120.110.14.nip.io/auth/"
  realm: "TheiaCloud"
  clientId: "theia-cloud"
  clientSecret: "RZdfb7bbhy26C6EObmvlHiZcZhar34O0"
  cookieSecret: "OQINaROshtE9TcZkNAm5Zs2Pv3xaWytBmc5W7sPX7ws="

operator:
  image: eu.gcr.io/kubernetes-238012/theia-cloud-operator
  eagerStart: false
  ephemeralStorage: true
  cloudProvider: "K8S"
  bandwidthLimiter: "K8SANNOTATION"