app:
  name: Landing Page Test Application
  # logo: test.svg use full path; not working yet after helm-repository switch

image:
  # name: theiacloud/theia-cloud-activity-demo:0.8.0.MS9-theia
  name: theiacloud/theia-cloud-activity-demo:0.8.0.MS9
  imagePullPolicy: IfNotPresent
  timeoutStrategy: "FIXEDTIME"
  timeoutLimit: "0"

hosts:
  usePaths: true
  paths:
    baseHost: 192.168.39.3.nip.io
    service: servicex
    landing: trynow
    instance: instances

landingPage:
  image: theiacloud/theia-cloud-landing-page:0.8.0.MS9
  imagePullPolicy: Always
  appDefinition: "theia-cloud-demo"
  ephemeralStorage: false

keycloak:
  enable: true
  authUrl: "https://keycloak.192.168.39.3.nip.io/auth/"
  realm: "TheiaCloud"
  clientId: "theia-cloud"
  clientSecret: "publicbutoauth2proxywantsasecret"
  cookieSecret: "OQINaROshtE9TcZkNAm5Zs2Pv3xaWytBmc5W7sPX7ws="

operator:
  cloudProvider: MINIKUBE
  imagePullPolicy: Always

service:
  imagePullPolicy: Always

ingress:
  clusterIssuer: theia-cloud-selfsigned-issuer
  theiaCloudCommonName: true

monitor:
  enable: true
  port: 8081
  activityTracker:
    enable: true
    interval: 1    
    timeoutAfter: 4
    notifyAfter: 2
