app:
  name: Landing Page Test Application
  # logo: test.svg use full path; not working yet after helm-repository switch

image:
  name: theiacloud/theia-cloud-activity-demo:0.8.0.MS8
  timeoutStrategy: "INACTIVITY"
  timeoutLimit: "3"
  imagePullPolicy: IfNotPresent

hosts:
  usePaths: false
  service: service.192.168.39.3.nip.io
  serviceProtocol: https
  landing: theia.cloud.192.168.39.3.nip.io
  instance: ws.192.168.39.3.nip.io

landingPage:
  image: theiacloud/theia-cloud-landing-page:0.8.0.MS8
  imagePullPolicy: Always
  appDefinition: "theia-cloud-demo"
  ephemeralStorage: false

keycloak:
  enable: true
  authUrl: "https://keycloak.192.168.39.3.nip.io/auth/"
  realm: "TheiaCloud"
  clientId: "theia-cloud"
  clientSecret: "publicbutoauth2proxywantsasecret"
  cookieSecret: "OQINaROshtE9TcZkNAm5Zs2Pv3xaWytBmc5W7sPX7ws="

operator:
  imagePullPolicy: Always

service:
  imagePullPolicy: Always

ingress:
  clusterIssuer: theia-cloud-selfsigned-issuer
  theiaCloudCommonName: true
