apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator-deployment
  labels:
    app: operator
  namespace: theiacloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operator
  template:
    metadata:
      labels:
        app: operator
    spec:
      # we need to be able to create and read operators
      automountServiceAccountToken: true
      serviceAccountName: operator-api-service-account
      containers:
      - name: operator-container
        image: gcr.io/kubernetes-238012/theia-cloud-operator