apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cert-deployment
  template:
    metadata:
      labels:
        app: cert-deployment
    spec:
      automountServiceAccountToken: false
      containers:
      - name: nginx-hello-world
        image: nginxdemos/hello
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cert-deployment-service
  labels:
    app: cert-deployment
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: cert-deployment
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cert-deployment-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    acme.cert-manager.io/http01-edit-in-place: "true"
    # cert-manager.io/common-name: "Theia.Cloud"
spec:
  tls:
  - hosts:
    - example.com
    secretName: default-tls
  rules:
  - host: example.com
    http:
      paths:
      - path: /cert
        pathType: Prefix
        backend:
          service:
            name: cert-deployment-service
            port:
              number: 80