extraEnv: |
  - name: PROXY_ADDRESS_FORWARDING
    value: "true"
  - name: KEYCLOAK_USER
    value: admin
  - name: KEYCLOAK_PASSWORD
    value: admin
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
  rules:
    - host: keycloak.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts: keycloak.example.com