apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth2-proxy-config
  namespace: theiacloud
data:
  oauth2-proxy.cfg: |+
    # Provider config
    provider="keycloak-oidc"
    redirect_url="https://placeholder/oauth2/callback"
    oidc_issuer_url="https://keycloak.192.168.99.113.nip.io/auth/realms/TheiaCloud"
    ssl_insecure_skip_verify=true
    # Client config
    client_id="theia-cloud"
    client_secret="1Wi13qJjXAOLUvBjiv7Pcxgh7WJblDLQ"
    cookie_secret="OQINaROshtE9TcZkNAm5Zs2Pv3xaWytBmc5W7sPX7ws="
    cookie_secure="false"
    #proxy_prefix=""
    # Upstream config
    http_address="0.0.0.0:5000"
    upstreams="http://127.0.0.1:3000/"
    # Proxy Config
    #user_id_claim="preferred_username"
    skip_auth_routes=["/health.*"]
    skip_provider_button="true"
    reverse_proxy="true"
    email_domains=["*"]
    cookie_domains=[".192.168.99.113.nip.io"]
    whitelist_domains=[".192.168.99.113.nip.io:*",".google.com:*"]
    custom_templates_dir="/templates"
