apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: appdefinitions.theia.cloud
spec:
  group: theia.cloud
  names:
    kind: AppDefinition
    listKind: AppDefinitionList
    plural: appdefinitions
    singular: appdefinition
  scope: Namespaced
  versions:
    - name : v2beta
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                image:
                  type: string
                pullSecret:
                  type: string
                uid:
                  type: integer
                port:
                  type: integer
                host:
                  type: string
                ingressname:
                  type: string
                minInstances:
                  type: integer
                maxInstances:
                  type: integer
                killAfter:
                  type: integer
                requestsMemory:
                  type: string
                requestsCpu:
                  type: string
                limitsMemory:
                  type: string
                limitsCpu:
                  type: string
                downlinkLimit:
                  type: integer
                uplinkLimit:
                  type: integer
    - name : v1beta
      served: true
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                image:
                  type: string
                uid:
                  type: integer
                port:
                  type: integer
                host:
                  type: string
                ingressname:
                  type: string
                minInstances:
                  type: integer
                maxInstances:
                  type: integer
                killAfter:
                  type: integer
                requestsMemory:
                  type: string
                requestsCpu:
                  type: string
                limitsMemory:
                  type: string
                limitsCpu:
                  type: string
                downlinkLimit:
                  type: integer
                uplinkLimit:
                  type: integer
                  