apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sessions.theia.cloud
spec:
  group: theia.cloud
  names:
    kind: Session
    listKind: SessionList
    plural: sessions
    singular: session
  scope: Namespaced
  versions:
    - name : v2beta
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                workspace:
                  type: string
                appDefinition: # cached from workspace
                  type: string
                user:          # cached from workspace
                  type: string
                url:
                  type: string
                error:
                  type: string
                lastActivity:
                  type: integer
    - name : v1beta
      served: true
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                appDefinition:
                  type: string
                user:
                  type: string
                url:
                  type: string
                error:
                  type: string
