apiVersion: v1
kind: ConfigMap
metadata:
  name: landing-page-config
  namespace: {{ .Release.Namespace }}
data:
  config.js: |
    window.theiaCloudConfig = {
      appId: "{{ .Values.app.id }}",
      appName: "{{ .Values.app.name }}",
      useKeycloak: {{ .Values.keycloak.enable }},
      keycloakAuthUrl: "{{ .Values.keycloak.authUrl }}",
      keycloakRealm: "{{ .Values.keycloak.realm }}",
      keycloakClientId: "{{ .Values.keycloak.clientId }}",
      workspaceServiceUrl: "https://{{ .Values.hosts.workspace }}/workspaces",
      workspaceTemplate: "{{ .Values.landingPage.template }}",
    };
binaryData:
  {{ range $path, $bytes := .Files.Glob (printf "logos/%s" .Values.app.logo)}}
  {{ print "logo.png: "}}{{ $.Files.Get $path | b64enc }}
  {{ end }}

