apiVersion: theia.cloud/v3beta
kind: AppDefinition
metadata:
  name: theia-cloud-demo
spec:
  name: theia-cloud-demo
  image: {{ .Values.image.name }}
  pullSecret: {{ .Values.image.pullSecret }}
  uid: {{ .Values.image.uid | default "101" }}
  port: 3000
  host: {{ tpl .Values.hosts.instance . }}
  ingressname: theia-cloud-demo-ws-ingress
  minInstances: 0
  maxInstances: 10
  timeout:
    limit: {{ .Values.image.timeoutLimit }}
    strategy: {{ .Values.image.timeoutStrategy }}
  requestsMemory: {{ .Values.image.requestsMemory | default "1000M" | quote }}
  limitsMemory: {{ .Values.image.limitsMemory | default "1000M" | quote }}
  requestsCpu: {{ .Values.image.requestsCpu | default "100m" | quote }}
  limitsCpu: {{ .Values.image.limitsCpu | default 2 | quote }}
  downlinkLimit: 30000
  uplinkLimit: 30000
  mountPath: "/projects"
