FROM theiacloud/theia-cloud-operator:latest

# Copy the customised templates into the /templates/ directory
COPY demo/dockerfiles/demo-operator-custom-template/templateDeployment.yaml /templates/
COPY demo/dockerfiles/demo-operator-custom-template/templateDeploymentWithoutOAuthProxy.yaml /templates/