name: "[MAVEN] maven-conf"

on:
  push:
    branches:
      - main
    paths:
      - "java/common/maven-conf/**"
  pull_request:
    branches:
      - main
    paths:
      - "java/common/maven-conf/**"
  release:
    types:
      - published

jobs:
  run:
    permissions:
      packages: write
    uses: ./.github/workflows/reusable-maven.yml
    with:
      path_to_package: common/maven-conf/
    secrets: inherit
