name: "[MAVEN] common"

on:
  push:
    branches:
      - main
    paths:
      - "java/common/**"
      # Run when a workflow has changed
      - ".github/workflows/ci-maven-common.yml"
      - ".github/workflows/reusable-maven.yml"
  pull_request:
    branches:
      - main
    paths:
      - "java/common/**"
      # Run when a workflow has changed
      - ".github/workflows/ci-maven-common.yml"
      - ".github/workflows/reusable-maven.yml"
  release:
    types:
      - published

jobs:
  run:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/reusable-maven.yml
    with:
      path_to_package: common/org.eclipse.theia.cloud.common/
