name: Try Now Page CI

on:
  push:
    branches:
      - main
    paths:
      - "node/common/**"
      - "node/try-now-page/**"
      - "dockerfiles/try-now-page/**"
  pull_request:
    branches:
      - main
    paths:
      - "node/common/**"
      - "node/try-now-page/**"
      - "dockerfiles/try-now-page/**"
  release:
    types:
      - published

jobs:
  call-reusable-docker-workflow:
    uses: ./.github/workflows/reusable-docker.yml
    with:
      docker_org: theiacloud
      docker_image: theia-cloud-try-now-page
      docker_file: dockerfiles/try-now-page/Dockerfile
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
