# Builds all theia extensions as well as the example extensions and example browser app.
name: "[THEIA] CI"

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/ci-theia.yml"
      - "theia/**/*"
      - "!theia/**/*.md"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/ci-theia.yml"
      - "theia/**/*"
      - "!theia/**/*.md"

permissions:
  contents: read

jobs:
  build:
    name: Build & Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./theia

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: theia/yarn.lock

      - name: Install dependencies
        run: |
          sudo apt-get install libsecret-1-dev
          yarn --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint
