# Builds all theia extensions as well as the example extensions and example browser app.
name: "[THEIA] CI"

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/ci-theia.yml"
      - "theia/**/*"
      - "!theia/**/*.md"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/ci-theia.yml"
      - "theia/**/*"
      - "!theia/**/*.md"

permissions:
  contents: read

jobs:
  build:
    name: Build & Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./theia

    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: theia/.nvmrc
          cache: yarn
          cache-dependency-path: theia/yarn.lock

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libsecret-1-dev
          yarn --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint
