name: "[DOCKER] wondershaper"

on:
  push:
    branches:
      - jf/openshift
  pull_request:
    branches:
      - main
    paths:
      - "dockerfiles/wondershaper/**"
  release:
    types:
      - published

jobs:
  run:
    uses: ./.github/workflows/reusable-docker.yml
    with:
      docker_org: theiacloud
      docker_image: theia-cloud-wondershaper
      docker_file: dockerfiles/wondershaper/Dockerfile
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
