name: Docker Wondershaper CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t theia-cloud-wondershaper:$(date +%s) -f dockerfiles/wondershaper/Dockerfile .
