name: Reusable workflow for npm packages

on:
  workflow_call:
    inputs:
      package_workspace:
        required: true
        type: string
        description: The package's workspace path relative to the node directory.

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    defaults:
      run:
        working-directory: ./node

    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: node/.nvmrc

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libsecret-1-dev
          npm ci

      - name: Build package
        run: npm run build -w ${{ inputs.package_workspace }}

  publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'release'
    defaults:
      run:
        working-directory: ./node
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Check version (only for push events)
        if: github.event_name == 'push'
        id: version_check
        run: |
          VERSION=$(cd ${{ inputs.package_workspace }} && node --print "require('./package.json').version")
          echo "Package version: ${VERSION}"
          if [[ $VERSION == *"-next" ]]; then
            echo "is_next_version=true" >> $GITHUB_OUTPUT
          else
            echo "is_next_version=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: node/.nvmrc
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libsecret-1-dev
          npm ci

      - name: Publish next version
        if: github.event_name == 'push' && steps.version_check.outputs.is_next_version == 'true'
        run: npm run publish:next -w ${{ inputs.package_workspace }}
        env:
          NPM_CONFIG_PROVENANCE: true

      - name: Publish latest version
        if: github.event_name == 'release'
        run: npm run publish:latest -w ${{ inputs.package_workspace }}
        env:
          NPM_CONFIG_PROVENANCE: true
