name: Reusable workflow publishing demo applications

on:
  workflow_call:
    inputs:
      docker_org:
        required: true
        type: string
      docker_image:
        required: true
        type: string
      docker_file:
        required: true
        type: string
      docker_location:
        required: true
        type: string
      publish_type:
        description: "Publish as latest ('latest') or next ('next')"
        required: true
        type: string
    secrets:
      dockerhub_username:
        required: true
      dockerhub_token:
        required: true

env:
  VERSION: 0.9.0

jobs:
  publish-next:
    runs-on: ubuntu-latest
    if: ${{ inputs.publish_type == 'next' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create docker tags
        id: get_tags
        run: |
          echo "sha_tag=${{ inputs.docker_org }}/${{ inputs.docker_image }}:${{ env.VERSION }}.$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT
          echo "version_tag=${{ inputs.docker_org }}/${{ inputs.docker_image }}:${{ env.VERSION }}" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: docker build -t ${{ steps.get_tags.outputs.version_tag }} -f ${{ inputs.docker_file }} ${{ inputs.docker_location }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.dockerhub_username }}
          password: ${{ secrets.dockerhub_token }}

      # Push version and SHA tag for main pushes of next versions (This avoids duplicate pushes for release commits on main)
      - name: Push version and SHA tag
        if: endsWith(env.VERSION, '-next')
        run: |
          docker push ${{ steps.get_tags.outputs.version_tag }}
          docker tag ${{ steps.get_tags.outputs.version_tag }} ${{ steps.get_tags.outputs.sha_tag }}
          docker push ${{ steps.get_tags.outputs.sha_tag }}

  publish-latest:
    runs-on: ubuntu-latest
    if: ${{ inputs.publish_type == 'latest' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create docker tags
        id: get_tags
        run: |
          echo "version_tag=${{ inputs.docker_org }}/${{ inputs.docker_image }}:${{ env.VERSION }}" >> $GITHUB_OUTPUT
          echo "next_tag=${{ inputs.docker_org }}/${{ inputs.docker_image }}:${{ env.VERSION }}-next" >> $GITHUB_OUTPUT
          echo "latest_tag=${{ inputs.docker_org }}/${{ inputs.docker_image }}:latest" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: docker build -t ${{ steps.get_tags.outputs.version_tag }} -f ${{ inputs.docker_file }} ${{ inputs.docker_location }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.dockerhub_username }}
          password: ${{ secrets.dockerhub_token }}

      # Push version, next and latest tag for releases (version should be valid semver)
      - name: Push version and latest tag
        run: |
          docker push ${{ steps.get_tags.outputs.version_tag }}
          docker tag ${{ steps.get_tags.outputs.version_tag }} ${{ steps.get_tags.outputs.latest_tag }}
          docker push ${{ steps.get_tags.outputs.latest_tag }}
          docker tag ${{ steps.get_tags.outputs.version_tag }} ${{ steps.get_tags.outputs.next_tag }} 
          docker push ${{ steps.get_tags.outputs.next_tag }}
