name: TheiaCloud Service CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build TheiaCloud common
      run: |
        mvn clean install -f java/common/maven-conf
        mvn clean install -f java/common/org.eclipse.theia.cloud.common
    - name: Run TheiaCloud service tests
      run: mvn clean verify -fae -f java/service/org.eclipse.theia.cloud.service

  docker:
    needs: tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t theia-cloud-service:$(date +%s) -f dockerfiles/service/Dockerfile .
