name: Service tests

on:
  push:
    branches:
      - main
    paths:
      - "java/common/**"
      - "java/service/**"
  pull_request:
    branches:
      - main
    paths:
      - "java/common/**"
      - "java/service/**"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      - name: Build TheiaCloud common
        run: |
          mvn clean install -f java/common/maven-conf --no-transfer-progress
          mvn clean install -f java/common/org.eclipse.theia.cloud.common --no-transfer-progress
      - name: Run TheiaCloud service tests
        run: mvn clean verify -fae -f java/service/org.eclipse.theia.cloud.service --no-transfer-progress
